### ISSUE TITLE
PlatformException Unsupported operation: Unrecognized JSON message

### ISSUE THREAD

**Issue by pulstar** [PlugFox/platform_info#4]
I am getting some errors in the browser console. Could you take a look to see if this have anything to do with your package? Thank you!

```
Overflow on channel: flutter/platform.  Messages on this channel are being discarded in FIFO fashion.  
The engine may not be running or you need to adjust the buffer size if of the channel.

_debugPrintWarning @ main.dart.js:14807
2main.dart.js:83242 Uncaught PlatformException(error, Unsupported operation: Unrecognized JSON message, null, null)
    at Object.wrapException (https://mydomain.com/main.dart.js:5717:17)
    at StandardMethodCodec.decodeEnvelope$1 (https://mydomain.com/main.dart.js:150799:17)
    at https://mydomain.com/main.dart.js:150916:46
    at _wrapJsFunctionForAsync_closure.$protected (https://mydomain.com/main.dart.js:9331:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://mydomain.com/main.dart.js:80220:12)
    at _awaitOnObject_closure.call$1 (https://mydomain.com/main.dart.js:80206:32)
    at _RootZone.runUnary$2$2 (https://mydomain.com/main.dart.js:83369:18)
    at _Future__propagateToListeners_handleValueCallback.call$0 (https://mydomain.com/main.dart.js:81173:51)
    at Object._Future__propagateToListeners (https://mydomain.com/main.dart.js:9582:93)
    at _Future._completeWithValue$1 (https://mydomain.com/main.dart.js:80995:9)
```

**Comment by PlugFox** [comment]
This is not my package's problem.
And has nothing to do with him.

**Comment by pulstar** [comment]
> This is not my package's problem.
> And has nothing to do with him.

Thank you for the help. I will look forward to find what is causing this.

**Comment by pulstar** [comment]
I found the culprit. It was any of the commands below, which should run only in Android.

```
SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
SystemChrome.setPreferredOrientations(Config.orientations);
Screen.keepOn(true);
Screen.setBrightness(Config.screenBrightness);
await FlutterIsolate.spawn(callback, params);
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
   statusBarColor: Config.statusBarColor,
   statusBarIconBrightness: Config.statusBarIconBrightness,
   systemNavigationBarColor: Config.systemNavigationBarColor,
   systemNavigationBarIconBrightness: Config.systemNavigationBarIconBrightness,
));
FirebaseMessaging fcm = FirebaseMessaging();
```
